[package]
name = "mmap-payload-storage"
version = "0.1.0"
edition = "2021"

[dependencies]
memmap2 = "0.9.4"
serde_json = "1.0.128"
serde = { version = "1.0.210", features = ["derive"] }
parking_lot = "0.12.3"
log = "0.4.22"
tempfile = "3.12.0"
serde_cbor = "0.11.2"