name: CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Rust CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install minimal stable
        uses: dtolnay/rust-toolchain@stable
      - name: Install nextest
        uses: taiki-e/install-action@nextest
      - name: Check code formatting
        run: cargo fmt --all -- --check
      - name: Build
        run: cargo build
      - name: Run tests
        run: cargo nextest run
      - name: Check cargo clippy warnings
        run: cargo clippy --workspace --all-targets --all-features -- -D warnings